created validToken()
RadiationChallengeProjectCAST/RadDataStorage pull request #16
Opened 2020-11-09 12:59 UTC by tomkettle1

This should work fine, but I can't test until I get docker set up w/ the database or whatever so @TimMcGilly would you mind checking this runs

2020-11-09 13:00 UTC, tomkettle1 commented
(Or @dislocated-su if you've got postgresql working on your machine)

2020-11-09 13:01 UTC, TimMcGilly commented
Will test in moment.

2020-11-09 13:08 UTC, TimMcGilly requested changes

2020-11-09 13:08 UTC, TimMcGilly commented on index.js
> +function validToken(token){
```suggestion
async function validToken(token){
```
Function needs to be async to have await in it.

2020-11-09 13:08 UTC, TimMcGilly commented on index.js
> +    });
Possible needs error handling?

2020-11-09 13:08 UTC, TimMcGilly commented on index.js
> +    else {return true;}
```suggestion
    return !result.rowCount === 0;
```

2020-11-09 13:10 UTC, TimMcGilly commented
This also break line 103 `const teamID = result.rows[0].teamid;` which gets team id but depends on query. Not sure best way to fix. Maybe change function to return teamID and if invalid it returns null. @dislocated-su Any thoughts?

2020-11-09 13:48 UTC, tomkettle1 commented
ok, fixed everything except adding error catching @TimMcGilly

2020-11-09 14:29 UTC, dislocated-su requested changes
Almost done, needs some minor changes.

2020-11-09 14:29 UTC, dislocated-su commented on index.js
> +async function validToken(token){
Function returns a teamid, not a boolean.
Name needs to reflect the fact that it returns a teamid.

2020-11-09 15:13 UTC, TimMcGilly commented on index.js
> +    else {return null;}
```suggestion
return null;
```
Doesn't need else.

2020-11-09 15:14 UTC, TimMcGilly commented
Will test on my side later once all changes including Andrey's are done.

2020-11-10 14:57 UTC, closed without merging

2020-11-10 16:57 UTC, TimMcGilly commented
Are we not using refactoring this anymore as it seemed like a good idea? @tomkettle1